### ISSUE TITLE
How to rebuild the scss

### ISSUE THREAD

**Issue by ScottChayaa** [xianmin/hugo-theme-jane#120]
Hi,
I want to modify  `src/css/_partial/_post/_footer.scss`
I already install `yarn` and `webpack`, and run
```sh
$ yarn run build
yarn run v1.9.4
$ webpack
(node:10333) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:10333) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'message' on string 'Checksum error in glyf'
    at /Users/scottchayaa/myblog/themes/jane/node_modules/iconfont-webpack-plugin/lib/loader.js:34:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 5.38s.
```

I don't know what the problem is it....
Could anyone help me?
Please give me some step how to rebuild the scss...@@"

**Comment by xianmin** [comment]
Maybe this link could help you? https://github.com/xianmin/hugo-theme-jane/wiki/How-to-Contribute

**Comment by voko** [comment]
> Hi,
> I want to modify `src/css/_partial/_post/_footer.scss`
> I already install `yarn` and `webpack`, and run

The issue was grounded in an unmaintained `transfoermation-matrix` module.
You'll see this when running `yarn install`:
```
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
warning iconfont-webpack-plugin > svgicons2svgfont > transformation-matrix-js@2.7.6: Package no longer supported. Contact support@npmjs.com for more info.
```
More details - for fun:D at https://www.npmjs.com/package/transformation-matrix-js.

### Solution
include a newer version of `svgicons2svgfont`that does not depend on `transformation-matrix` anymore. 

Here's my `themes/jane/package.json`:

```json
{
  "name": "hugo-theme-jane",
  "version": "1.2.0",
  "description": "A simple theme for hugo",
  "main": "",
  "scripts": {
    "build": "webpack",
    "demo": "hugo --contentDir='./exampleSite/content' --config='dev-config.toml' ",
    "dev:assets": "webpack --watch --display='errors-only' ",
    "dev:site": "hugo server --buildDrafts --contentDir='./exampleSite/content' --config='dev-config.toml' ",
    "dev": "concurrently 'npm run dev:assets' 'npm run dev:site' ",
    "clean": "rm -rf ./public",
    "contributors:add": "all-contributors add",
    "contributors:generate": "all-contributors generate"
  },
  "author": "xianmin",
  "license": "MIT",
  "devDependencies": {
    "all-contributors-cli": "^4.11.1",
    "autoprefixer": "^8.1.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "concurrently": "^3.5.1",
    "fsevents": "^1.2.4",
    "css-loader": "^0.28.10",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "^3.0.0",
    "iconfont-webpack-plugin": "^3.0.1",
    "svgicons2svgfont":"^9.0.3",
    "file-loader": "^1.1.11",
    "node-sass": "^4.10.0",
    "postcss-loader": "^2.1.1",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.20.2",
    "uglifyjs-webpack-plugin": "^1.2.2",
    "url-loader": "^1.0.1",
    "webpack": "^3.11.0"
  },
  "dependencies": {}
}
```

The important entry is `"svgicons2svgfont":"^9.0.3"`, after that a build works just fine.

### successful build output
```
$ yarn run build
yarn run v1.12.3
$ webpack
Hash: c4f8a2e64542dc7f9e40
Version: webpack 3.12.0
Time: 4293ms
                                      Asset     Size  Chunks             Chunk Names
  fonts/chancery/apple-chancery-webfont.eot  26.1 kB          [emitted]
fonts/chancery/apple-chancery-webfont.woff2  23.5 kB          [emitted]
 fonts/chancery/apple-chancery-webfont.woff  30.3 kB          [emitted]
  fonts/chancery/apple-chancery-webfont.ttf  60.8 kB          [emitted]
  fonts/chancery/apple-chancery-webfont.svg  74.3 kB          [emitted]
                                jane.min.js  4.56 kB       0  [emitted]  jane
                               jane.min.css  38.5 kB       0  [emitted]  jane
                            jane.min.js.map  13.6 kB       0  [emitted]  jane
                           jane.min.css.map   121 kB       0  [emitted]  jane
   [0] ./js/main.js 969 bytes {0} [built]
   [1] ./css/style.scss 41 bytes {0} [built]
   [2] ./js/backToTop.js 400 bytes {0} [built]
   [3] ./js/mobileNavbar.js 1.5 kB {0} [built]
   [4] ./js/toc.js 750 bytes {0} [built]
   [5] ./js/headerAnchor.js 1.41 kB {0} [built]
   [6] ./js/footnoteTooltip.js 1.03 kB {0} [built]
   [7] ./js/highlight.js 767 bytes {0} [built]
   [8] ../node_modules/css-loader??ref--1-2!../node_modules/postcss-loader/lib??ref--1-3!../node_modules/sass-loader/lib/loader.js??ref--1-4!./css/style.scss 159 kB [built]
  [12] ./fonts/chancery/apple-chancery-webfont.eot 87 bytes [built]
  [13] ./fonts/chancery/apple-chancery-webfont.woff2 89 bytes [built]
  [14] ./fonts/chancery/apple-chancery-webfont.woff 88 bytes [built]
  [15] ./fonts/chancery/apple-chancery-webfont.ttf 87 bytes [built]
  [16] ./fonts/chancery/apple-chancery-webfont.svg 87 bytes [built]
    + 5 hidden modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--1-2!../node_modules/postcss-loader/lib/index.js??ref--1-3!../node_modules/sass-loader/lib/loader.js??ref--1-4!css/style.scss:
     5 assets
       [0] ./fonts/chancery/apple-chancery-webfont.eot 87 bytes {0} [built]
       [1] ../node_modules/css-loader??ref--1-2!../node_modules/postcss-loader/lib??ref--1-3!../node_modules/sass-loader/lib/loader.js??ref--1-4!./css/style.scss 159 kB {0} [built]
       [5] ./fonts/chancery/apple-chancery-webfont.woff2 89 bytes {0} [built]
       [6] ./fonts/chancery/apple-chancery-webfont.woff 88 bytes {0} [built]
       [7] ./fonts/chancery/apple-chancery-webfont.ttf 87 bytes {0} [built]
       [8] ./fonts/chancery/apple-chancery-webfont.svg 87 bytes {0} [built]
        + 3 hidden modules
✨  Done in 5.42s.
```
